### ISSUE TITLE
Milford map needs new pgw file

### ISSUE THREAD

**Issue by holloway** [holloway/greatwalks-builder#15]
As you've changed the map file you'll need to provide a new PGW file to describe that graphic,

This is the current one which will now be out of sync with the map graphic,

https://github.com/holloway/greatwalks-builder/blob/master/walks/Milford%20Track/map.pgw

**Comment by cameronrose** [comment]
A new PGW file has been included with the new map. Included in latest commit.

**Comment by holloway** [comment]
Thanks, will assume this fixes it and do an app rebuild soon.
